version: '3.8'

services:
  app-prod:
    build:
      context: .
      target: production
    container_name: arvancloud-blog-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://api-3281216083-arvancloud-challenge.apps.ir-central1.arvancaas.ir/api
    restart: unless-stopped
    networks:
      - arvancloud-network

networks:
  arvancloud-network:
    driver: bridge