version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      target: dev
    container_name: arvancloud-blog-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=https://api-3281216083-arvancloud-challenge.apps.ir-central1.arvancaas.ir/api
    networks:
      - arvancloud-network
    restart: unless-stopped

  # Production service
  app-prod:
    build:
      context: .
      target: production
    container_name: arvancloud-blog-prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    networks:
      - arvancloud-network
    restart: unless-stopped
    profiles:
      - production

  # Optional: Reverse proxy (only when using --profile proxy)
  nginx-proxy:
    image: nginx:alpine
    container_name: arvancloud-proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-dev
      - app-prod
    networks:
      - arvancloud-network
    profiles:
      - proxy

networks:
  arvancloud-network:
    driver: bridge