version: '3.8'

services:
  app-dev:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_HOST=localhost
      - VITE_DEBUGGER=false
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.git